// Re-export all domain types from the contract IR
export type {
  SignalKind,
  SignalErrorCode,
  SignalErrorCategory,
  SignalError,
  SignalSuccess,
  SignalFailure,
  SignalResult,
  SignalResultMeta,
  Note,
  NoteGetInput,
  NoteGetResult,
  Post,
  PostGetInput,
  PostGetResult,
  PostPublishInput,
  PostPublishResult,
  PaymentRiskDeclaration,
  PaymentMethodInput,
  PaymentCaptureInput,
  PaymentCaptureResult,
  PaymentCaptureGetInput,
  PaymentAuditEntry,
  PaymentCaptureGetResult,
  PaymentCapturedEvent,
  ReferenceCertificationCheck,
  ReferenceCertificationResult,
  DecisionEvidence,
  DecisionRecord,
  CommitmentResult,
  SignalOperationCapability,
  SignalCapabilities,
} from "../../../contracts/domain-types";