#!/bin/zsh
set -euo pipefail

PROJECT_DIR="/Users/diogoangelim/signal/examples/stocks-optimizer"
ENV_FILE="${PROJECT_DIR}/.env.local"
LOG_DIR="${PROJECT_DIR}/.local-cache/logs"
STATE_DIR="${PROJECT_DIR}/.local-cache/binance-execution"

mkdir -p "${LOG_DIR}" "${STATE_DIR}"
cd "${PROJECT_DIR}"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  source "${ENV_FILE}"
  set +a
fi

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"



export BINANCE_MODE="${BINANCE_MODE:-testnet}"
export BINANCE_LIVE_TRADING_ENABLED="${BINANCE_LIVE_TRADING_ENABLED:-false}"
export BINANCE_CONFIRM_LIVE_TRADING="${BINANCE_CONFIRM_LIVE_TRADING:-false}"
export BINANCE_RISK_GUARD_LIVE_TRADING_APPROVED="${BINANCE_RISK_GUARD_LIVE_TRADING_APPROVED:-false}"

export BINANCE_ALLOWED_SYMBOLS="${BINANCE_ALLOWED_SYMBOLS:-*}"
export BINANCE_WORKER_AUTO_EXECUTE="true"
export BINANCE_WORKER_INTERVAL_MS="${BINANCE_WORKER_INTERVAL_MS:-60000}"
export BINANCE_WORKER_MARKET="${BINANCE_WORKER_MARKET:-BINANCE}"
export BINANCE_WORKER_STRATEGY_ID="${BINANCE_WORKER_STRATEGY_ID:-stocks-optimizer}"
export BINANCE_WORKER_LIMIT="${BINANCE_WORKER_LIMIT:-20}"
export BINANCE_WORKER_REQUIRE_IGNORE_BASELINE="${BINANCE_WORKER_REQUIRE_IGNORE_BASELINE:-true}"
export BINANCE_WORKER_IGNORE_BASELINE_FILE="${BINANCE_WORKER_IGNORE_BASELINE_FILE:-${STATE_DIR}/ignored-current-signals.json}"
export BINANCE_WORKER_CLEARED_SIGNALS_FILE="${BINANCE_WORKER_CLEARED_SIGNALS_FILE:-${STATE_DIR}/cleared-signals.json}"
export STOCKS_OPTIMIZER_BASE_URL="${STOCKS_OPTIMIZER_BASE_URL:-https://stocks-optimizer.vercel.app}"
export STOCKS_OPTIMIZER_EXECUTION_SECRET="${STOCKS_OPTIMIZER_EXECUTION_SECRET:-${BINANCE_EXECUTION_ADMIN_SECRET:-}}"
export BINANCE_WORKER_ADMIN_SECRET="${BINANCE_WORKER_ADMIN_SECRET:-${BINANCE_EXECUTION_ADMIN_SECRET:-}}"
export BINANCE_EXECUTION_STATE_FILE="${BINANCE_EXECUTION_STATE_FILE:-${STATE_DIR}/${BINANCE_MODE}-state.json}"
export BINANCE_TAKE_PROFIT_ENABLED="${BINANCE_TAKE_PROFIT_ENABLED:-false}"
export BINANCE_TAKE_PROFIT_FEE_BPS="${BINANCE_TAKE_PROFIT_FEE_BPS:-20}"
export BINANCE_TAKE_PROFIT_BUFFER_BPS="${BINANCE_TAKE_PROFIT_BUFFER_BPS:-5}"
export BINANCE_TAKE_PROFIT_ORDER_TYPE="${BINANCE_TAKE_PROFIT_ORDER_TYPE:-LIMIT}"
export PORT="${PORT:-8787}"

exec /opt/homebrew/bin/pnpm worker:start
